// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: VanSightDisplayClient

#include "ui.h"

// Event implementations are in src/ui_event_handlers.cpp (for ESP32)
// or ui_event_handlers.c (for simulator)
