// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: VanSightDisplayClient

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void onBtnHomeClick(lv_event_t * e);
void onBtnLeftChairClick(lv_event_t * e);
void onBtnRightChairClick(lv_event_t * e);
void onBtnKitchenClick(lv_event_t * e);
void onBtnToiletClick(lv_event_t * e);
void onBtnBathClick(lv_event_t * e);
void onBtnBedClick(lv_event_t * e);
void onBtnBalkonyUpClick(lv_event_t * e);
void onBtnBalkonyDownClick(lv_event_t * e);
void onBtnProjectorClick(lv_event_t * e);
void onBtnReloadInformationClick(lv_event_t * e);
void onBtnCloseAllClick(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
