// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: VanSightDisplayClient

#ifndef _VANSIGHTDISPLAYCLIENT_UI_H
#define _VANSIGHTDISPLAYCLIENT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_vanSightScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_images_bg_png);    // assets/images/bg.png

// FONTS
LV_FONT_DECLARE(ui_font_FaRegular);
LV_FONT_DECLARE(ui_font_FontAwsome7Solid);
LV_FONT_DECLARE(ui_font_Roboto);
LV_FONT_DECLARE(ui_font_fasolid);
LV_FONT_DECLARE(ui_font_rubikwetpaint);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
