// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: VanSightDisplayClient

#ifndef _UI_COMP_RELAYBUTTON_H
#define _UI_COMP_RELAYBUTTON_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT RelayButton
#define UI_COMP_RELAYBUTTON_RELAYBUTTON 0
#define UI_COMP_RELAYBUTTON_LABEL2 1
#define _UI_COMP_RELAYBUTTON_NUM 2
lv_obj_t * ui_RelayButton_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
