// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: VanSightDisplayClient

#ifndef UI_VANSIGHTSCREEN_H
#define UI_VANSIGHTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_vanSightScreen
extern void ui_vanSightScreen_screen_init(void);
extern void ui_vanSightScreen_screen_destroy(void);
extern lv_obj_t * ui_vanSightScreen;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_lblTitle;
extern lv_obj_t * ui_LevelContainer1;
extern lv_obj_t * ui_ButtonContainer;
extern void ui_event_btnHome_RelayButton(lv_event_t * e);
extern lv_obj_t * ui_btnHome;
extern void ui_event_btnLeftChair_RelayButton(lv_event_t * e);
extern lv_obj_t * ui_btnLeftChair;
extern void ui_event_btnRightChair_RelayButton(lv_event_t * e);
extern lv_obj_t * ui_btnRightChair;
extern void ui_event_btnKitchen_RelayButton(lv_event_t * e);
extern lv_obj_t * ui_btnKitchen;
extern void ui_event_btnToilet_RelayButton(lv_event_t * e);
extern lv_obj_t * ui_btnToilet;
extern void ui_event_btnBath_RelayButton(lv_event_t * e);
extern lv_obj_t * ui_btnBath;
extern void ui_event_btnBed_RelayButton(lv_event_t * e);
extern lv_obj_t * ui_btnBed;
extern void ui_event_btnBalkonyUp_RelayButton(lv_event_t * e);
extern lv_obj_t * ui_btnBalkonyUp;
extern void ui_event_btnBalkonyDown_RelayButton(lv_event_t * e);
extern lv_obj_t * ui_btnBalkonyDown;
extern void ui_event_btnProjector_RelayButton(lv_event_t * e);
extern lv_obj_t * ui_btnProjector;
extern void ui_event_btnReloadInformation_RelayButton(lv_event_t * e);
extern lv_obj_t * ui_btnReloadInformation;
extern void ui_event_btnCloseAll_RelayButton(lv_event_t * e);
extern lv_obj_t * ui_btnCloseAll;
extern lv_obj_t * ui_LevelContainer;
extern lv_obj_t * ui_CleanWaterLevel;
extern lv_obj_t * ui_lblCleanWaterPercentage;
extern lv_obj_t * ui_barCleanWaterLevel;
extern lv_obj_t * ui_LabelIcon;
extern lv_obj_t * ui_LabelName;
extern lv_obj_t * ui_GrayWaterLevel;
extern lv_obj_t * ui_lblGrayWaterPercentage;
extern lv_obj_t * ui_barGrayWaterLevel;
extern lv_obj_t * ui_LabelIcon1;
extern lv_obj_t * ui_LabelName1;
extern lv_obj_t * ui_BlackWaterLevel;
extern lv_obj_t * ui_lblBlackWaterPercentage;
extern lv_obj_t * ui_barBlackWaterLevel;
extern lv_obj_t * ui_LabelIcon2;
extern lv_obj_t * ui_LabelName2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

