// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: VanSightDisplayClient

#include "ui.h"

lv_obj_t * ui_vanSightScreen = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_lblTitle = NULL;
lv_obj_t * ui_LevelContainer1 = NULL;
lv_obj_t * ui_ButtonContainer = NULL;
lv_obj_t * ui_btnHome = NULL;
lv_obj_t * ui_btnLeftChair = NULL;
lv_obj_t * ui_btnRightChair = NULL;
lv_obj_t * ui_btnKitchen = NULL;
lv_obj_t * ui_btnToilet = NULL;
lv_obj_t * ui_btnBath = NULL;
lv_obj_t * ui_btnBed = NULL;
lv_obj_t * ui_btnBalkonyUp = NULL;
lv_obj_t * ui_btnBalkonyDown = NULL;
lv_obj_t * ui_btnProjector = NULL;
lv_obj_t * ui_btnReloadInformation = NULL;
lv_obj_t * ui_btnCloseAll = NULL;
lv_obj_t * ui_LevelContainer = NULL;
lv_obj_t * ui_CleanWaterLevel = NULL;
lv_obj_t * ui_lblCleanWaterPercentage = NULL;
lv_obj_t * ui_barCleanWaterLevel = NULL;
lv_obj_t * ui_LabelIcon = NULL;
lv_obj_t * ui_LabelName = NULL;
lv_obj_t * ui_GrayWaterLevel = NULL;
lv_obj_t * ui_lblGrayWaterPercentage = NULL;
lv_obj_t * ui_barGrayWaterLevel = NULL;
lv_obj_t * ui_LabelIcon1 = NULL;
lv_obj_t * ui_LabelName1 = NULL;
lv_obj_t * ui_BlackWaterLevel = NULL;
lv_obj_t * ui_lblBlackWaterPercentage = NULL;
lv_obj_t * ui_barBlackWaterLevel = NULL;
lv_obj_t * ui_LabelIcon2 = NULL;
lv_obj_t * ui_LabelName2 = NULL;
// event funtions

// build funtions

void ui_vanSightScreen_screen_init(void)
{
    ui_vanSightScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_vanSightScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_vanSightScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_vanSightScreen, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_img_src(ui_vanSightScreen, &ui_img_images_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_vanSightScreen, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_vanSightScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_vanSightScreen, 220, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_vanSightScreen);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(100));
    lv_obj_set_height(ui_Container1, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Container1, -7);
    lv_obj_set_y(ui_Container1, -185);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblTitle = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_lblTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTitle, -363);
    lv_obj_set_y(ui_lblTitle, -7);
    lv_obj_set_align(ui_lblTitle, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_lblTitle, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_lblTitle, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_lblTitle, "AVAREYOLCULAR");
    lv_obj_set_style_text_color(ui_lblTitle, lv_color_hex(0x19FC00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTitle, &ui_font_rubikwetpaint, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LevelContainer1 = lv_obj_create(ui_vanSightScreen);
    lv_obj_remove_style_all(ui_LevelContainer1);
    lv_obj_set_width(ui_LevelContainer1, lv_pct(100));
    lv_obj_set_flex_grow(ui_LevelContainer1, 1);
    lv_obj_set_y(ui_LevelContainer1, 0);
    lv_obj_set_x(ui_LevelContainer1, lv_pct(25));
    lv_obj_set_align(ui_LevelContainer1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LevelContainer1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LevelContainer1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LevelContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonContainer = lv_obj_create(ui_LevelContainer1);
    lv_obj_remove_style_all(ui_ButtonContainer);
    lv_obj_set_width(ui_ButtonContainer, 320);
    lv_obj_set_height(ui_ButtonContainer, lv_pct(100));
    lv_obj_set_x(ui_ButtonContainer, -210);
    lv_obj_set_y(ui_ButtonContainer, 0);
    lv_obj_set_align(ui_ButtonContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ButtonContainer, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ButtonContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_ButtonContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnHome = ui_RelayButton_create(ui_ButtonContainer);
    lv_obj_set_x(ui_btnHome, -89);
    lv_obj_set_y(ui_btnHome, -54);

    lv_label_set_text(ui_comp_get_child(ui_btnHome, UI_COMP_RELAYBUTTON_LABEL2), "");

    ui_btnLeftChair = ui_RelayButton_create(ui_ButtonContainer);
    lv_obj_set_x(ui_btnLeftChair, -89);
    lv_obj_set_y(ui_btnLeftChair, -54);

    lv_label_set_text(ui_comp_get_child(ui_btnLeftChair, UI_COMP_RELAYBUTTON_LABEL2), "");

    ui_btnRightChair = ui_RelayButton_create(ui_ButtonContainer);
    lv_obj_set_x(ui_btnRightChair, 15);
    lv_obj_set_y(ui_btnRightChair, -56);

    lv_label_set_text(ui_comp_get_child(ui_btnRightChair, UI_COMP_RELAYBUTTON_LABEL2), "");

    ui_btnKitchen = ui_RelayButton_create(ui_ButtonContainer);
    lv_obj_set_x(ui_btnKitchen, 15);
    lv_obj_set_y(ui_btnKitchen, -56);

    lv_label_set_text(ui_comp_get_child(ui_btnKitchen, UI_COMP_RELAYBUTTON_LABEL2), "");

    ui_btnToilet = ui_RelayButton_create(ui_ButtonContainer);
    lv_obj_set_x(ui_btnToilet, 15);
    lv_obj_set_y(ui_btnToilet, -56);

    lv_label_set_text(ui_comp_get_child(ui_btnToilet, UI_COMP_RELAYBUTTON_LABEL2), "");

    ui_btnBath = ui_RelayButton_create(ui_ButtonContainer);
    lv_obj_set_x(ui_btnBath, 15);
    lv_obj_set_y(ui_btnBath, -56);

    lv_label_set_text(ui_comp_get_child(ui_btnBath, UI_COMP_RELAYBUTTON_LABEL2), "");

    ui_btnBed = ui_RelayButton_create(ui_ButtonContainer);
    lv_obj_set_x(ui_btnBed, 15);
    lv_obj_set_y(ui_btnBed, -56);

    lv_label_set_text(ui_comp_get_child(ui_btnBed, UI_COMP_RELAYBUTTON_LABEL2), "");

    ui_btnBalkonyUp = ui_RelayButton_create(ui_ButtonContainer);
    lv_obj_set_x(ui_btnBalkonyUp, 15);
    lv_obj_set_y(ui_btnBalkonyUp, -56);

    lv_label_set_text(ui_comp_get_child(ui_btnBalkonyUp, UI_COMP_RELAYBUTTON_LABEL2), "");

    ui_btnBalkonyDown = ui_RelayButton_create(ui_ButtonContainer);
    lv_obj_set_x(ui_btnBalkonyDown, 15);
    lv_obj_set_y(ui_btnBalkonyDown, -56);

    lv_label_set_text(ui_comp_get_child(ui_btnBalkonyDown, UI_COMP_RELAYBUTTON_LABEL2), "");

    ui_btnProjector = ui_RelayButton_create(ui_ButtonContainer);
    lv_obj_set_x(ui_btnProjector, 15);
    lv_obj_set_y(ui_btnProjector, -56);

    lv_label_set_text(ui_comp_get_child(ui_btnProjector, UI_COMP_RELAYBUTTON_LABEL2), "");

    ui_btnReloadInformation = ui_RelayButton_create(ui_ButtonContainer);
    lv_obj_set_x(ui_btnReloadInformation, 80);
    lv_obj_set_y(ui_btnReloadInformation, -40);

    lv_label_set_text(ui_comp_get_child(ui_btnReloadInformation, UI_COMP_RELAYBUTTON_LABEL2), "");

    ui_btnCloseAll = ui_RelayButton_create(ui_ButtonContainer);
    lv_obj_set_x(ui_btnCloseAll, 15);
    lv_obj_set_y(ui_btnCloseAll, -56);

    lv_label_set_text(ui_comp_get_child(ui_btnCloseAll, UI_COMP_RELAYBUTTON_LABEL2), "");

    ui_LevelContainer = lv_obj_create(ui_LevelContainer1);
    lv_obj_remove_style_all(ui_LevelContainer);
    lv_obj_set_height(ui_LevelContainer, lv_pct(100));
    lv_obj_set_flex_grow(ui_LevelContainer, 1);
    lv_obj_set_y(ui_LevelContainer, 0);
    lv_obj_set_x(ui_LevelContainer, lv_pct(25));
    lv_obj_set_align(ui_LevelContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LevelContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LevelContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LevelContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CleanWaterLevel = lv_obj_create(ui_LevelContainer);
    lv_obj_remove_style_all(ui_CleanWaterLevel);
    lv_obj_set_width(ui_CleanWaterLevel, 100);
    lv_obj_set_height(ui_CleanWaterLevel, 400);
    lv_obj_set_x(ui_CleanWaterLevel, -44);
    lv_obj_set_y(ui_CleanWaterLevel, 5);
    lv_obj_set_align(ui_CleanWaterLevel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CleanWaterLevel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CleanWaterLevel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CleanWaterLevel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_CleanWaterLevel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_CleanWaterLevel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCleanWaterPercentage = lv_label_create(ui_CleanWaterLevel);
    lv_obj_set_width(ui_lblCleanWaterPercentage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCleanWaterPercentage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCleanWaterPercentage, -3);
    lv_obj_set_y(ui_lblCleanWaterPercentage, -200);
    lv_obj_set_align(ui_lblCleanWaterPercentage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCleanWaterPercentage, "80%");
    lv_obj_set_style_text_color(ui_lblCleanWaterPercentage, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCleanWaterPercentage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCleanWaterPercentage, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barCleanWaterLevel = lv_bar_create(ui_CleanWaterLevel);
    lv_bar_set_value(ui_barCleanWaterLevel, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barCleanWaterLevel, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barCleanWaterLevel, 57);
    lv_obj_set_flex_grow(ui_barCleanWaterLevel, 1);
    lv_obj_set_x(ui_barCleanWaterLevel, 2);
    lv_obj_set_y(ui_barCleanWaterLevel, -30);
    lv_obj_set_align(ui_barCleanWaterLevel, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_barCleanWaterLevel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barCleanWaterLevel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barCleanWaterLevel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_barCleanWaterLevel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_barCleanWaterLevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_barCleanWaterLevel, lv_color_hex(0x9F85FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_barCleanWaterLevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_barCleanWaterLevel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_barCleanWaterLevel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barCleanWaterLevel, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelIcon = lv_label_create(ui_CleanWaterLevel);
    lv_obj_set_width(ui_LabelIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIcon, 0);
    lv_obj_set_y(ui_LabelIcon, 154);
    lv_obj_set_align(ui_LabelIcon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIcon, "");
    lv_obj_set_style_text_color(ui_LabelIcon, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelIcon, &ui_font_FontAwsome7Solid, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelName = lv_label_create(ui_CleanWaterLevel);
    lv_obj_set_width(ui_LabelName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelName, 8);
    lv_obj_set_y(ui_LabelName, 200);
    lv_obj_set_align(ui_LabelName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelName, "Temiz Su");
    lv_obj_set_style_text_color(ui_LabelName, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelName, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GrayWaterLevel = lv_obj_create(ui_LevelContainer);
    lv_obj_remove_style_all(ui_GrayWaterLevel);
    lv_obj_set_width(ui_GrayWaterLevel, 100);
    lv_obj_set_height(ui_GrayWaterLevel, 400);
    lv_obj_set_x(ui_GrayWaterLevel, 69);
    lv_obj_set_y(ui_GrayWaterLevel, 4);
    lv_obj_set_align(ui_GrayWaterLevel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_GrayWaterLevel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_GrayWaterLevel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GrayWaterLevel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_GrayWaterLevel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_GrayWaterLevel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblGrayWaterPercentage = lv_label_create(ui_GrayWaterLevel);
    lv_obj_set_width(ui_lblGrayWaterPercentage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblGrayWaterPercentage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblGrayWaterPercentage, -3);
    lv_obj_set_y(ui_lblGrayWaterPercentage, -200);
    lv_obj_set_align(ui_lblGrayWaterPercentage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblGrayWaterPercentage, "80%");
    lv_obj_set_style_text_color(ui_lblGrayWaterPercentage, lv_color_hex(0xB4B6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblGrayWaterPercentage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblGrayWaterPercentage, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barGrayWaterLevel = lv_bar_create(ui_GrayWaterLevel);
    lv_bar_set_value(ui_barGrayWaterLevel, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barGrayWaterLevel, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barGrayWaterLevel, 57);
    lv_obj_set_flex_grow(ui_barGrayWaterLevel, 1);
    lv_obj_set_x(ui_barGrayWaterLevel, 2);
    lv_obj_set_y(ui_barGrayWaterLevel, -30);
    lv_obj_set_align(ui_barGrayWaterLevel, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_barGrayWaterLevel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barGrayWaterLevel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barGrayWaterLevel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_barGrayWaterLevel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_barGrayWaterLevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_barGrayWaterLevel, lv_color_hex(0xB6B6B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_barGrayWaterLevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_barGrayWaterLevel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_barGrayWaterLevel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barGrayWaterLevel, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barGrayWaterLevel, lv_color_hex(0xB4B6B4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barGrayWaterLevel, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelIcon1 = lv_label_create(ui_GrayWaterLevel);
    lv_obj_set_width(ui_LabelIcon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIcon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIcon1, 0);
    lv_obj_set_y(ui_LabelIcon1, 154);
    lv_obj_set_align(ui_LabelIcon1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIcon1, "");
    lv_obj_set_style_text_color(ui_LabelIcon1, lv_color_hex(0xB4B6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelIcon1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelIcon1, &ui_font_FontAwsome7Solid, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelName1 = lv_label_create(ui_GrayWaterLevel);
    lv_obj_set_width(ui_LabelName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelName1, 8);
    lv_obj_set_y(ui_LabelName1, 200);
    lv_obj_set_align(ui_LabelName1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelName1, "Gri Su");
    lv_obj_set_style_text_color(ui_LabelName1, lv_color_hex(0xB4B6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelName1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelName1, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BlackWaterLevel = lv_obj_create(ui_LevelContainer);
    lv_obj_remove_style_all(ui_BlackWaterLevel);
    lv_obj_set_width(ui_BlackWaterLevel, 100);
    lv_obj_set_height(ui_BlackWaterLevel, 400);
    lv_obj_set_x(ui_BlackWaterLevel, -139);
    lv_obj_set_y(ui_BlackWaterLevel, -9);
    lv_obj_set_align(ui_BlackWaterLevel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BlackWaterLevel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BlackWaterLevel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BlackWaterLevel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_BlackWaterLevel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BlackWaterLevel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBlackWaterPercentage = lv_label_create(ui_BlackWaterLevel);
    lv_obj_set_width(ui_lblBlackWaterPercentage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBlackWaterPercentage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBlackWaterPercentage, -3);
    lv_obj_set_y(ui_lblBlackWaterPercentage, -200);
    lv_obj_set_align(ui_lblBlackWaterPercentage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBlackWaterPercentage, "80%");
    lv_obj_set_style_text_color(ui_lblBlackWaterPercentage, lv_color_hex(0xFF4C4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBlackWaterPercentage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBlackWaterPercentage, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barBlackWaterLevel = lv_bar_create(ui_BlackWaterLevel);
    lv_bar_set_value(ui_barBlackWaterLevel, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barBlackWaterLevel, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barBlackWaterLevel, 57);
    lv_obj_set_flex_grow(ui_barBlackWaterLevel, 1);
    lv_obj_set_x(ui_barBlackWaterLevel, 2);
    lv_obj_set_y(ui_barBlackWaterLevel, -30);
    lv_obj_set_align(ui_barBlackWaterLevel, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_barBlackWaterLevel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barBlackWaterLevel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barBlackWaterLevel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_barBlackWaterLevel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_barBlackWaterLevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_barBlackWaterLevel, lv_color_hex(0xFA4C4E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_barBlackWaterLevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_barBlackWaterLevel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_barBlackWaterLevel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barBlackWaterLevel, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barBlackWaterLevel, lv_color_hex(0xFA4C4E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barBlackWaterLevel, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelIcon2 = lv_label_create(ui_BlackWaterLevel);
    lv_obj_set_width(ui_LabelIcon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIcon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIcon2, 0);
    lv_obj_set_y(ui_LabelIcon2, 154);
    lv_obj_set_align(ui_LabelIcon2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIcon2, "");
    lv_obj_set_style_text_color(ui_LabelIcon2, lv_color_hex(0xFF4C4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelIcon2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelIcon2, &ui_font_FontAwsome7Solid, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelName2 = lv_label_create(ui_BlackWaterLevel);
    lv_obj_set_width(ui_LabelName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelName2, 8);
    lv_obj_set_y(ui_LabelName2, 200);
    lv_obj_set_align(ui_LabelName2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelName2, "Pis Su");
    lv_obj_set_style_text_color(ui_LabelName2, lv_color_hex(0xFF4C4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelName2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelName2, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_vanSightScreen_screen_destroy(void)
{
    if(ui_vanSightScreen) lv_obj_del(ui_vanSightScreen);

    // NULL screen variables
    ui_vanSightScreen = NULL;
    ui_Container1 = NULL;
    ui_lblTitle = NULL;
    ui_LevelContainer1 = NULL;
    ui_ButtonContainer = NULL;
    ui_btnHome = NULL;
    ui_btnLeftChair = NULL;
    ui_btnRightChair = NULL;
    ui_btnKitchen = NULL;
    ui_btnToilet = NULL;
    ui_btnBath = NULL;
    ui_btnBed = NULL;
    ui_btnBalkonyUp = NULL;
    ui_btnBalkonyDown = NULL;
    ui_btnProjector = NULL;
    ui_btnReloadInformation = NULL;
    ui_btnCloseAll = NULL;
    ui_LevelContainer = NULL;
    ui_CleanWaterLevel = NULL;
    ui_lblCleanWaterPercentage = NULL;
    ui_barCleanWaterLevel = NULL;
    ui_LabelIcon = NULL;
    ui_LabelName = NULL;
    ui_GrayWaterLevel = NULL;
    ui_lblGrayWaterPercentage = NULL;
    ui_barGrayWaterLevel = NULL;
    ui_LabelIcon1 = NULL;
    ui_LabelName1 = NULL;
    ui_BlackWaterLevel = NULL;
    ui_lblBlackWaterPercentage = NULL;
    ui_barBlackWaterLevel = NULL;
    ui_LabelIcon2 = NULL;
    ui_LabelName2 = NULL;

}
