// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: VanSightDisplayClient

#include "ui.h"

// COMPONENT RelayButton

lv_obj_t * ui_RelayButton_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_RelayButton;
    cui_RelayButton = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_RelayButton, 85);
    lv_obj_set_height(cui_RelayButton, 85);
    lv_obj_set_x(cui_RelayButton, -89);
    lv_obj_set_y(cui_RelayButton, -54);
    lv_obj_set_align(cui_RelayButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_RelayButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_RelayButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(cui_RelayButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_RelayButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_RelayButton, lv_color_hex(0x240CFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_RelayButton, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_RelayButton, lv_color_hex(0x9F85FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_RelayButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_RelayButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_RelayButton, &ui_font_FontAwsome7Solid, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label2;
    cui_Label2 = lv_label_create(cui_RelayButton);
    lv_obj_set_width(cui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label2, -157);
    lv_obj_set_y(cui_Label2, -130);
    lv_obj_set_align(cui_Label2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Label2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Label2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(cui_Label2, "");
    lv_obj_set_style_text_color(cui_Label2, lv_color_hex(0x868686), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label2, &ui_font_FontAwsome7Solid, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_RELAYBUTTON_NUM);
    children[UI_COMP_RELAYBUTTON_RELAYBUTTON] = cui_RelayButton;
    children[UI_COMP_RELAYBUTTON_LABEL2] = cui_Label2;
    lv_obj_add_event_cb(cui_RelayButton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_RelayButton, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_RelayButton_create_hook(cui_RelayButton);
    return cui_RelayButton;
}

